apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  params:
    - name: git-url
      value: "https://github.com/avnish2313/budget-app-tekton.git"
    - name: docker-image
      value: "avnish2313/final:latest"
  serviceAccountName: default
  timeout: "1h"