apiVersion: v1
kind: Service
metadata:
  name: budget-app
spec:
  selector:
    app: budget-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: budget-app-db
spec:
  selector:
    app: budget-app-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
